# MINUET LIGHT ACCESSORY COMMON DECLARATIONS
#
# Do not include this file directly.
minuet_light_common:
  esphome:
    includes:
      - minuet/light-accessory/light-accessory.h
    on_boot:
      - priority: 500
        then:
        - lambda: |-
            id(minuet_keypad_accessory_toggle) = []() -> bool {
              minuet::light_accessory::toggle(id(minuet_light));
              return true;
            };

            id(minuet_keypad_accessory_up) = []() -> bool {
              minuet::light_accessory::change_brightness(id(minuet_light), 1);
              return true;
            };

            id(minuet_keypad_accessory_down) = []() -> bool {
              minuet::light_accessory::change_brightness(id(minuet_light), -1);
              return true;
            };

            id(minuet_ir_control_accessory_nec) = [](esphome::remote_base::NECData code) {
              minuet::light_accessory::apply_nec_code(id(minuet_light), code);
            };
