# MINUET LIGHT ACCESSORY PACKAGE
# VARIANT: DIMMABLE LIGHT
# SUPPORTED HARDWARE: Minuet Light Accessory v3.0
#
# Supports a dimmable light connected to the accessory board.
# Refer to the accessory documentation for details.
#
# Include the contents of this file into your device configuration YAML
# file as a package like this:
#
# packages:
#   <<: !include
#     file: minuet/light-accessory/dimmable-light.yaml
#     vars:
#       minuet_light_accessory_board_version: 'v3_0'
#
# Set `minuet_board_version` according to the silkscreen label printed on your Minuet board.
minuet_light:
  # Dimmable light.
  light:
    - id: minuet_light
      name: Light
      platform: monochromatic
      output: minuet_light_pwm
      restore_mode: ALWAYS_OFF
      default_transition_length: 0.5s
      effects:
        - pulse:

  # PWM output for drives the PWR pin.
  output:
    - id: minuet_light_pwm
      platform: ledc
      pin:
        number: ${minuet_light_pin_power}
        mode: output
      channel: 0
      frequency: 1000 Hz

  # Shutdown behavior: Turn off the light before ESPHome restarts.
  esphome:
    on_shutdown:
      - priority: 500
        then:
          - lambda: |-
              id(minuet_light_pwm).turn_off();

<<: !include common.yaml
