# MINUET WIFI-SWITCH PACKAGE
#
# ESPHome package to control whether wifi is enabled or disabled.
# Assumes that the wifi component exists and has the id 'minuet_wifi'.
#
# Include the contents of this file into your device configuration YAML
# file as a package like this (recommended):
#
# packages:
#   <<: !include
#     file: minuet/wifi-switch.yaml
#     vars:
#       default_state: 'OFF'
#
# The default state can be 'OFF' or 'ON' and it takes effect when the firmware is first
# installed and after a factory reset.  It is recommended to set the default state to
# 'OFF' for security when using a captive portal and no WiFi credentials have been configured.
minuet_wifi_switch:
  switch:
    - id: minuet_wifi_switch
      name: "WiFi Enable"
      icon: mdi:wifi
      platform: template
      optimistic: true
      restore_mode: RESTORE_DEFAULT_${default_state}
      entity_category: config
      disabled_by_default: true
      on_turn_on:
        then:
          - wifi.enable:
      on_turn_off:
        then:
          - wifi.disable:
  esphome:
    on_boot:
      - priority: 500
        then:
        - lambda: |-
            id(minuet_keypad_wifi_switch) = id(minuet_wifi_switch);
            id(minuet_wifi).set_enable_on_boot(id(minuet_wifi_switch).state);
