# MINUET OFFLINE CONFIGURATION
#
# ESPHome device configuration for operating Minuet without any WiFi at all.
# Control Minuet with the control panel, IR remote, or wall control.
#
# Please modify this configuration and secrets.yaml to suit your needs.
esphome:
  name: minuet
  friendly_name: Minuet

# Configure logging.
logger:
  level: DEBUG
  # Set to 0 to disable serial port log output and improve performance
  # Set to 921600 to enable serial port log output for debugging
  baud_rate: 0

# Organize the configuration into packages for extensibility.
packages:
  # Include the core logic (required).
  <<: !include
    file: minuet/core.yaml
    vars:
      minuet_board_version: 'v3_0'

  # Include configuration for an accessory plugged into the expansion port (optional).
  # Choose at most one of these packages to uncomment.
  # <<: !include
  #   file: minuet/light-accessory/addressable-led-strip.yaml
  #   vars:
  #     minuet_light_accessory_board_version: 'v3_0'
  #     minuet_led_strip: 'btf_sk6812_rgbw_60'
  # <<: !include
  #   file: minuet/light-accessory/dimmable-light.yaml
  #   vars:
  #     minuet_light_accessory_board_version: 'v3_0'

  # Add more packages here to support for your custom features.
  # my_package:
  #   sensors:
  #     - platform: scd4x
  #       i2c_id: minuet_i2c
