# MINUET KIT CONFIGURATION
#
# This is the default configuration programmed at the factory for a kit that includes the
# Minuet board, lighting accessory, and addressable LED lights.
#
# ESPHome device configuration for operating Minuet with a WiFi captive portal
# and a simple web based user interface for a connected out-of-the-box experience.
#
# After connecting to the access point, open http://192.168.4.1/ in a web browser
# to set the wifi credentials and access the user interface.
#
# Please modify this configuration and secrets.yaml to suit your needs.
esphome:
  name: minuet
  friendly_name: Minuet

# Configure logging.
logger:
  level: DEBUG
  baud_rate: 921600

# Set up a WiFi access point and captive portal for out-of-the-box wireless configuration.
wifi:
  id: minuet_wifi
  ap:
    ssid: !secret minuet_access_point_ssid
    password: !secret minuet_access_point_password
    ap_timeout: 1min
  power_save_mode: light

captive_portal:

# Enable over-the-air software updates.
ota:
  - platform: esphome
    password: !secret minuet_over_the_air_update_password

# Enable the ESPHome API to control the device and retrieve logs.
# Typically used by ESPHome Builder and Home Assistant.
api:
  encryption:
    key: !secret minuet_api_encryption_key

# Organize the configuration into packages for extensibility.
packages:
  # Include the core logic (required).
  <<: !include minuet/core.yaml

  # Include the switch for enabling or disabling wifi (optional).
  <<: !include
    file: minuet/wifi-switch.yaml
    vars:
      default_state: 'OFF'

  # Include the web interface (optional).
  <<: !include minuet/web.yaml

  # Include configuration for an accessory plugged into the expansion port (optional).
  # Choose at most one of these packages to uncomment.
  <<: !include
    file: minuet/light-accessory/addressable-led-strip.yaml
    vars:
      name: 'Light'
      num_leds: 19
      chipset: WS2811
      rgb_order: RGB
      is_wrgb: true
      is_rgbw: false
  # <<: !include
  #   file: minuet/light-accessory/dimmable-light.yaml
  #   vars:
  #     name: 'Light'

  # Add more packages here to support for your custom features.
  # my_package:
  #   sensors:
  #     - platform: scd4x
  #       i2c_id: minuet_i2c
