# MINUET OFFLINE CONFIGURATION
#
# ESPHome device configuration for operating Minuet without any WiFi at all.
# Control Minuet with the control panel, IR remote, or wall control.
#
# Please modify this configuration and secrets.yaml to suit your needs.
esphome:
  name: minuet
  friendly_name: Minuet

# Configure logging.
logger:
  level: DEBUG
  baud_rate: 921600

# Organize the configuration into packages for extensibility.
packages:
  # Include the core logic (required).
  <<: !include minuet/core.yaml

  # Include configuration for an accessory plugged into the expansion port (optional).
  # Choose at most one of these packages to uncomment.
  # <<: !include
  #   file: minuet/light-accessory/addressable-led-strip.yaml
  #   vars:
  #     name: 'Light'
  #     num_leds: 40
  #     chipset: WS2811
  #     rgb_order: RGB
  #     is_wrgb: true
  #     is_rgbw: false
  # <<: !include
  #   file: minuet/light-accessory/dimmable-light.yaml
  #   vars:
  #     name: 'Light'

  # Add more packages here to support for your custom features.
  # my_package:
  #   sensors:
  #     - platform: scd4x
  #       i2c_id: minuet_i2c
