# MINUET OFFLINE CONFIGURATION
#
# ESPHome device configuration for operating Minuet without any WiFi at all.
# Control Minuet with the control panel, IR remote, or wall control.
#
# Please modify this configuration and secrets.yaml to suit your needs.
esphome:
  name: minuet
  friendly_name: Minuet

# Configure logging.
logger:
  level: DEBUG
  baud_rate: 921600

# Organize the configuration into packages for extensibility.
packages:
  # Include the core logic.
  <<: !include minuet/core.yaml

  # Define more packages here to support your accessories.
  #
  # my_package:
  #   sensors:
  #     - platform: scd4x
  #       i2c_id: minuet_i2c
