# MINUET INTEGRATED CONFIGURATION
#
# ESPHome device configuration for connecting Minuet to an existing WiFi network
# and integrated it with Home Assistant or some other front-end using the ESPHome API
# instead of the built-in standalone web interface.
#
# Please modify this configuration and secrets.yaml to suit your needs.
esphome:
  name: minuet
  friendly_name: Minuet

# Configure logging.
logger:
  level: DEBUG
  baud_rate: 921600

# Set up WiFi to connect to your network.
wifi:
  id: minuet_wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: light
  fast_connect: true

# Enable over-the-air software updates.
ota:
  - platform: esphome
    password: !secret minuet_over_the_air_update_password

# Enable the ESPHome API to control the device and retrieve logs.
# Typically used by ESPHome Builder and Home Assistant.
api:
  encryption:
    key: !secret minuet_api_encryption_key

# Organize the configuration into packages for extensibility.
packages:
  # Include the core logic.
  <<: !include minuet/core.yaml
  # Uncomment to include the web interface if you need it.
  # <<: !include minuet/web.yaml

  # Define more packages here to support your accessories.
  #
  # my_package:
  #   sensors:
  #     - platform: scd4x
  #       i2c_id: minuet_i2c
