# Use this file to store secrets like usernames and passwords.

# Credentials for the WiFi network that Minuet and other ESPHome devices
# should automatically connect to.
wifi_ssid: "Change Me"
wifi_password: "Change Me"

# Credentials for the WiFi access point that Minuet sets up for out-of-the-box
# configuration in standalone mode.  The Minuet captive portal asks the user
# to provide new credentials when they connect to the access point for the
# first time and after a factory reset.
minuet_access_point_ssid: "Minuet"
minuet_access_point_password: "IAmAFan!"

# The password to authorize over-the-air firmware updates for Minuet.
# It can be any string of characters.
minuet_over_the_air_update_password: "379584e3bac0c0e59bcf1069dea603c4"

# The encryption key to authorize use of the ESPHome API for Minuet to control the
# device and retrieve logs.  Typically used by ESPHome Builder and Home Assistant.
# It is a random 32 byte base 64 encoded string.
# See https://esphome.io/components/api.html#configuration-variables for
# instructions to generate a new encryption key.
minuet_api_encryption_key: "q9CVZmO8RWgjc9Ix53YTgXHnUCzK6kj60O4M3njceyk="
